from typing import TypedDict, List

class AgentState(TypedDict):
    # Orignal User Question
    question : str

    # Retrieved chunks (From vectorDB or web search)
    chunks : List[str]

    # Final answer generated by the LLM
    answer : str

    # Which tool was used to get the answer
    source_used : str # web_search | vector_db_search